### ISSUE TITLE
Temporary directory left over after first install

### ISSUE THREAD

**Issue by ericvanbuhler** [alwaysai/cli#16]
After the initial app target install, there is a temporary directory left in the app directory tree on the device.

Here is my target config:
```
$ cat alwaysai.target.json
{
  "hostname": "alwaysai@alwaysai10",
  "username": "alwaysai",
  "password": "alwaysai",
  "privateKeyPath": "/home/eric/.ssh/id_rsa_test",
  "path": "/home/alwaysai/dashboard_app",
  "protocol": "ssh:"
}
```

Here is my local directory:
```
$ ls
alwaysai.app.json  alwaysai.target.json  app.py  dashboard.py  requirements.txt  templates
```
Here is my remote directory:
```
$ ls
alwaysai.app.json     app.py        models            templates  venv
alwaysai.target.json  dashboard.py  requirements.txt  tmp
```

**Comment by carnesen** [comment]
Yeah let's def clean up after ourselves better than we are now. As of this writing, here is the relevant section of code https://github.com/alwaysai/cli/blob/d31545729105590f3c01bd92c6756e7d49a26821/src/subcommands/app/target/install-models.ts#L37 .  Concretely,  if we want to use an app sandbox subdirectory as a temporary space we should name the directory `.tmp` instead of `tmp` so that if we fail to clean up it's less obvious to the user. Even better would be to enhance the `Spawner` API to include some functionality around temporary files/directories. The JS implementation would be `tempy`, which is already a dependency. The GNU implementation would be a wrapper around  `mktemp`, which we are already using in unit tests.

**Comment by carnesen** [comment]
Now we name the temporary directory more sensibly and also attempt to clean it up https://github.com/alwaysai/cli/blob/42c1f4b85c62c6760b2a70e9022f4988e39889e3/src/app-installer/install-models.ts#L69
