### ISSUE TITLE
problem during app target install if ssh key problematic

### ISSUE THREAD

**Issue by ryanmalone** [alwaysai/cli#42]
Just ran into the problem again of an app not installing when there is a problem with the ssh key on the remote host (install to docker on remote raspberry pi)... 

Gets stuck on application source install point if there are 2 ssh keys installed with the same ip:
Warning: the ECDSA host key for 'alwaysaipi01' differs from the key for the IP address 'x.x.x.x'
Offending key for IP in /Users/xxx/.ssh/known_hosts:3
Matching host key in /Users/xxx/.ssh/known_hosts:4

**Comment by carnesen** [comment]
@ryanmalone I think I follow, but I'm not 100%. Can edit your description with "steps to reproduce"?

**Comment by carnesen** [comment]
I chatted with @ryanmalone about this. The issue was not with the key used for user authentication but with the keys used for host verification. He had connected to a board via its IP address and accepted the host key's fingerprint. Then later he connected to a board with that same IP address but a different host key (it had been re-flashed or something).
